// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfKUX8k6ZVBqxbNesPk150h--oteZvTH0',
    appId: '1:822662017715:web:517deff4ddce1179ed76c6',
    messagingSenderId: '822662017715',
    projectId: 'nrg-trade',
    authDomain: 'nrg-trade.firebaseapp.com',
    storageBucket: 'nrg-trade.firebasestorage.app',
    measurementId: 'G-NX4T4Y1TDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlTq53b42ipC-EVcr8lHuEjH6OuR2nXLg',
    appId: '1:822662017715:android:081aee514f1b44f5ed76c6',
    messagingSenderId: '822662017715',
    projectId: 'nrg-trade',
    storageBucket: 'nrg-trade.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTTQucgD-ZSlCD_3ckDa5VYGoXsPqL-4Y',
    appId: '1:822662017715:ios:af09a3cbff04d571ed76c6',
    messagingSenderId: '822662017715',
    projectId: 'nrg-trade',
    storageBucket: 'nrg-trade.firebasestorage.app',
    iosBundleId: 'com.example.energyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTTQucgD-ZSlCD_3ckDa5VYGoXsPqL-4Y',
    appId: '1:822662017715:ios:af09a3cbff04d571ed76c6',
    messagingSenderId: '822662017715',
    projectId: 'nrg-trade',
    storageBucket: 'nrg-trade.firebasestorage.app',
    iosBundleId: 'com.example.energyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfKUX8k6ZVBqxbNesPk150h--oteZvTH0',
    appId: '1:822662017715:web:e6ccc3714004102bed76c6',
    messagingSenderId: '822662017715',
    projectId: 'nrg-trade',
    authDomain: 'nrg-trade.firebaseapp.com',
    storageBucket: 'nrg-trade.firebasestorage.app',
    measurementId: 'G-TN3NBLG5QH',
  );
}
